#!/bin/sh

##
# Script gets and shows on Kindle png file generated by backend
#
# author: Tomasz Ceszke
##


BAT=$(/usr/bin/gasgauge-info -c | grep -o '[0-9]*')
PNG_URL="http://demo.ceszke.com/kindle-weather/cgi-bin/getweatherpng.py?bat=${BAT}"


#if $(/usr/bin/powerd_test -s | grep -q Active); then
#       echo 'Already active'
#else
#        /usr/bin/powerd_test -p
#fi
#/sbin/ifconfig wlan0 up
#/bin/sleep 60


/bin/rm /tmp/kindle.png
/usr/bin/wget -q -O /tmp/kindle.png ${PNG_URL}

if [ "$1" = "clear" ]; then
        /usr/sbin/eips -c
        /usr/bin/lipc-set-prop com.lab126.powerd preventScreenSaver 1
fi
/usr/sbin/eips -g /tmp/kindle.png


#/usr/sbin/eips ''
#if $(/usr/bin/powerd_test -s | grep -q Active); then
#/usr/bin/powerd_test -p
#fi
#/sbin/ifconfig wlan0 down
